apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt-label
  template:
    metadata:
      labels:
        app: zigbee2mqtt-label
    spec:
      containers:
      - name: zigbee2mqtt
        image: ghcr.io/koenkk/zigbee2mqtt:stable
        ports:
        - containerPort: 8080
          name: zigbee2mqtt-web
        volumeMounts:
        - mountPath: /app/data/
          name: data
        resources:
          limits:
            akri.sh/akri-radio: "1"
          requests:
            akri.sh/akri-radio: "1"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zigbee2mqtt-pv-data
