apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zigbee2mqtt-label
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zigbee2mqtt-label
    spec:
      containers:
      - name: zigbee2mqtt
        image: ghcr.io/koenkk/zigbee2mqtt:stable
        ports:
        - containerPort: 8080
          name: z2m-web
        volumeMounts:
        - mountPath: /app/data/
          name: data
        {{- if .Values.zigbee2mqtt.radio.akri.enabled }}
        resources:
          limits:
            akri.sh/{{ .Values.zigbee2mqtt.radio.akri.instance }}: "1"
          requests:
            akri.sh/{{ .Values.zigbee2mqtt.radio.akri.instance }}: "1"
        {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zigbee2mqtt-pv-data
