---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: zigbee2mqtt-label
  ports:
  - name: zigbee2mqtt
    protocol: TCP
    port: {{ .Values.zigbee2mqtt.ingress.servicePort }}
    targetPort: zigbee2mqtt-web
