---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zigbee2mqtt-zfs-sc
  namespace: {{ .Release.Namespace }}
parameters:
  recordsize: "128k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: "zfspv-pool"
provisioner: zfs.csi.openebs.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-pv-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: zigbee2mqtt-label
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zigbee2mqtt-zfs-sc
  resources:
    requests:
      storage: {{ (.Values.zigbee2mqtt.volume.data).size | default "16Gi" }}
