apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-radio
  namespace: akri
  labels:
    app.kubernetes.io/name: zigbee2mqtt-label
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |+
      groupRecursive: true
      udevRules:
      - 'ATTRS{idVendor}=="{{ .Values.zigbee2mqtt.radio.vendorId }}", ATTRS{idProduct}=="{{ .Values.zigbee2mqtt.radio.productId }}"'
    name: udev
