homeassistant:
  ingress:
    subDomain: ha
    servicePort: 80
  volume:
    data:
      size: 64Gi
    time:
      size: 8Gi

zigbee2mqtt:
  ingress:
    subDomain: z2m
    servicePort: 80
  radio:
    vendorId: 10c4
    productId: ea60
  volume:
    data:
      size: 16Gi

mosquitto:
  ingress:
    subDomain: mqtt
    websocketPort: 9001
    tlsPort: 8883
  account:
    username: admin
    password: changeme
  volume:
    data:
      size: 8Gi

network:
  certmanager:
    letsencryptEmail: admin@parksbra.com
  ingress:
    host: parkl.ee

akri:
  kubernetesDistro: k8s
  udev:
    discovery:
      enabled: true

openebs:
  engines:
    replicated:
      mayastor:
        enabled: false
  zfs-localpv:
    zfsNode:
      kubeletDir: /var/lib/kubelet

zfs:
  poolName: zfspv-pool
