services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - "{{ zigbee2mqtt_config_path }}:/app/data:rw"
      - "/run/udev:/run/udev:ro"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8234:8080
    environment:
      - TZ=America/Los_Angeles
      - PUID=1001
      - PGID=1001
    networks:
      - homeassistant_zigbee2mqtt
      - mqtt5_connection
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:8080']