apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.network.certmanager.clusterissuer.acme.email }}
    privateKeySecretRef:
      key: private-key
      name: cluster-issuer-letsencrypt-key
    solvers:
    - dns01:
        {{ .Values.network.certmanager.clusterissuer.dns01.provider }}:
          email: {{ .Values.network.certmanager.clusterissuer.dns01.cloudflare.email }}
          apiTokenSecretRef:
            name: {{ .Values.network.certmanager.clusterissuer.dns01.cloudflare.apiTokenSecretName }}
            key: {{ .Values.network.certmanager.clusterissuer.dns01.cloudflare.apiKTokenSecretKey }}
