apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosquitto
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.network.ingress.host }}
    secretName: external-cert
  rules:
  - host: "{{ .Values.homeassistant.ingress.subDomain }}.{{ .Values.network.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ha-web
            port: 
              number: {{ .Values.homeassistant.ingress.servicePort }}
  - host: "{{ .Values.mosquitto.ingress.subDomain }}.{{ .Values.network.ingress.host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mosquitto-ws
            port:
              number: {{ .Values.mosquitto.ingress.websocketPort }}
  - host: "{{ .Values.zigbee2mqtt.ingress.subDomain }}.{{ .Values.network.ingress.host }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: zigbee2mqtt-web
            port:
              number: {{ .Values.zigbee2mqtt.ingress.servicePort }}
