homeassistant:
  ingress:
    servicePort: 8123
    nodePort: 38123
    subDomain: ha
  storage:
    reclaimPolicy: Delete
  volume:
    data:
      size: 16Gi
    time:
      size: 8Gi
  config:
    configuration: |
      default_config:
      logger:
        default: info
      automation: !include automations.yaml
      script: !include scripts.yaml
      scene: !include scenes.yaml
      group: !include groups.yaml

zfs:
  poolName: zfspv-pool
