services:
  mqtt5:
    image: x
    container_name: mqtt5
    environment:
      - TZ=America/Los_Angeles
      - PUID=1001
      - PGID=1001
    ports:
      - 9001:9001
    volumes:
      - "{{ mqtt5_config_path }}:/mosquitto/config:rw"
      - "{{ mqtt5_data_path }}:/mosquitto/data:rw"
      - "{{ mqtt5_log_path }}:/mosquitto/log:rw"
    networks:
      - mqtt5_connection
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:1883']
