apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config-map
  namespace: {{ .Release.Namespace }}
data:
  configuration.yaml: |
    {{ .Values.homeassistant.config.configuration | nindent 4 }}
