---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant-label
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homeassistant-label
    spec:
      hostNetwork: true
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:stable
        ports:
          - containerPort: 8123
            name: ha-web
        resources: {}
        volumeMounts:
          - mountPath: /config
            name: homeassistant-pv-config
          - mountPath: /etc/localtime
            name: homeassistant-pv-time
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: homeassistant-pv-config
          persistentVolumeClaim:
            claimName: homeassistant-pv-config
        - name: homeassistant-pv-time
          persistentVolumeClaim:
            claimName: homeassistant-pv-time
            readOnly: true
