---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant-label
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homeassistant-label
    spec:
      initContainers:
      - name: setup-dependent-config-files
        image: busybox:latest
        command: ["sh", "-c"]
        args:
          - touch /config/automations.yaml /config/scripts.yaml /config/scenes.yaml /config/groups.yaml
        volumeMounts:
          - mountPath: /config
            name: homeassistant-data
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:stable
        ports:
          - containerPort: 8123
            name: ha-web
        resources: {}
        volumeMounts:
          - mountPath: /config/configuration.yaml
            subPath: configuration.yaml
            name: homeassistant-config-map
          - mountPath: /config
            name: homeassistant-data
          - mountPath: /etc/localtime
            name: homeassistant-time
            readOnly: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      volumes:
        - name: homeassistant-config-map
          configMap:
            name: homeassistant-config-map
        - name: homeassistant-data
          persistentVolumeClaim:
            claimName: homeassistant-pvc-data
        - name: homeassistant-time
          persistentVolumeClaim:
            claimName: homeassistant-pvc-time
            readOnly: true
