---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: homeassistant-label
  ports:
  - name: homeassistant
    port: {{ (.Values.homeassistant.service).port }}
    targetPort: homeassistant-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ (.Values.homeassistant.ingress).host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: homeassistant-service
            port:
              number: {{ (.Values.homeassistant.service).port }}
