---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: homeassistant-label
  ports:
  - name: ha-web
    protocol: TCP
    port: {{ .Values.homeassistant.ingress.servicePort }}
    targetPort: ha-web
    nodePort: {{ .Values.homeassistant.ingress.nodePort }}
