---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: homeassistant-zfs-sc
  namespace: {{ .Release.Namespace }}
parameters:
  recordsize: "128k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: {{ .Values.zfs.poolName }}
reclaimPolicy: Retain
provisioner: zfs.csi.openebs.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc-time
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homeassistant-label
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homeassistant-zfs-sc
  resources:
    requests:
      storage: {{ .Values.homeassistant.volume.time.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homeassistant-label
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homeassistant-zfs-sc
  resources:
    requests:
      storage: {{ .Values.homeassistant.volume.data.size }}
