zigbee2mqtt:
  ingress:
    subDomain: z2m
    servicePort: 80
    nodePort: 38234
  radio:
    vendorId: ffff
    productId: ffff
    enableAkri: false
    akri:
      enabled: true
      instance: akri-udev
  volume:
    data:
      size: 16Gi

zfs:
  poolName: zfspv-pool
