zigbee2mqtt:
  ingress:
    host: zigbee2mqtt.local
    servicePort: 443
  radio:
    vendorId: ffff
    productId: ffff
  volume:
    data:
      size: 16Gi

akri:
  kubernetesDistro: k8s
  udev:
    discovery:
      enabled: true

zfs:
  poolName: zfspv-pool
