services:
  nut_upsd:
    image: instantlinux/nut-upsd
    container_name: nut_upsd
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - DRIVER=usbhid-ups
      - NAME=upsST625U
      - VENDORID=0x0764
      - POLLINTERVAL=15
      - MAXAGE=45
    devices:
      - /dev/bus/usb:/dev/bus/usb
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:3493']
    volumes:
      - "{{ nut_upsd_config_path }}:/config:rw"
    restart: unless-stopped
    networks:
      - homeassistant_nut_upsd