apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto-label
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto-label
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 8883
          name: mqtt-tls
        - containerPort: 9001
          name: mqtt-websocket
        volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
          name: mosquitto-config-map
        - mountPath: /mosquitto/certs/
          name: mosquitto-cert
        - mountPath: /mosquitto/data/
          name: mosquitto-data
        - mountPath: /mosquitto/config/password.txt
          subPath: password.txt
          name: mosquitto-password
      dnsPolicty: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: mosquitto-config-map
        configMap:
          name: mosquitto-config-map
      - name: mosquitto-password
        configMap:
          name: mosquitto-password
      - name: mosquitto-cert
        secret:
          secretName: external-cert
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-pvc-data
