---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: homeassistant
spec:
  selector:
    app: mosquitto-label
  ports:
  - name: mqtt5
    port: 8883
    targetPort: mqtt
  - name: mqtt5-websocket
    port: 9001
    targetPort: mqtt-websocket
