---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mosquitto-label
  ports:
  - name: mqtt5
    port: {{ (.Values.mosquitto).tlsPort }}
    targetPort: mqtt-tls
  - name: mqtt5-websocket
    port: {{ (.Values.mosquitto).websocketPort }}
    targetPort: mqtt-websocket
