apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-password-file
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password.txt: "{{ .Values.mosquitto.account.username }}:{{ .Values.mosquitto.account.password }}"
