---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: mosquitto-label
  ports:
  - name: mqtt5
    port: {{ .Values.mosquitto.ingress.tlsPort }}
    targetPort: mqtt-tls
  - name: mqtt5-websocket
    protocol: TCP
    port: {{ .Values.mosquitto.ingress.websocketPort }}
    targetPort: mqtt-websocket
