---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mosquitto-zfs-sc
  namespace: {{ .Release.Namespace }}
parameters:
  recordsize: "128k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: {{ .Values.zfs.poolName }}
reclaimPolicy: Retain
provisioner: zfs.csi.openebs.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv-data
spec:
  capacity:
    storage: {{ .Values.mosquitto.volume.data.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: mosquitto-zfs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: zfs.csi.openebs.io
    volumeHandle: mosquitto-pv-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mosquitto-label
spec:
  volumeName: mosquitto-pv-data
  accessModes:
    - ReadWriteOnce
  storageClassName: mosquitto-zfs-sc
  resources:
    requests:
      storage: {{ .Values.mosquitto.volume.data.size }}
