services:
  openwrt:
    container_name: openwrt
    image: albrechtloh/openwrt-docker
    restart: unless-stopped
    ports:
      - 8006:8006
      # - 8000:8000
    environment:
      - TZ=America/Los_Angeles
      - PUID=1001
      - PGID=1001
      - WAN_IF=host
      - LAN_IF=veth
      # - WAN_IF=eth0
      # - LAN_IF=eth1
      # - PCI_1=0001:01:00.0
      # - PCI_2=0002:01:00.0
      - FORWARD_LUCI=true
      - CPU_COUNT=4
      - RAM_COUNT=4096
      - IMAGE_SIZE_ON_INIT=16384
      - DEBUG=true
    devices:
      - /dev/kvm
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    pid: "host"
    privileged: true
    volumes:
      - "/dev:/dev/:rw"
      - "data:/storage/:rw"


volumes:
  data: