services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
      - DISABLE_JEMALLOC=true
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:8123/manifest.json']
    volumes:
      - "{{ homeassistant_config_path }}:/config:rw"
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - homeassistant_backend
      - homeassistant_swag
      - homeassistant_zigbee2mqtt
      - homeassistant_nut_upsd
      - mqtt5_connection
